FROM nvidia/cuda:9.0-devel-ubuntu16.04

ENV CUDNN_VERSION=7.0.5.15-1+cuda9.0
ENV NCCL_VERSION=2.2.13-1+cuda9.0

RUN apt-get update && apt-get install -y --no-install-recommends --allow-downgrades --allow-change-held-packages \
        build-essential \
        cmake \
        git \
        curl \
        nano \
        wget \
        unzip \
        ca-certificates \
		jq \
        locales \
        apt-transport-https \
        software-properties-common \
        libcudnn7=${CUDNN_VERSION} \
        libjpeg-dev \
        libpng-dev \
        ffmpeg \
        tmux

COPY environment.yml .

ENV ENV_NAME=py36
RUN curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh && \
     /opt/conda/bin/conda env create -q --name $ENV_NAME -f environment.yml && \
     /opt/conda/bin/conda clean -ya && \
     ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \ 
     echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \ 
     echo "conda activate $ENV_NAME" >> ~/.bashrc
ENV PATH /opt/conda/envs/$ENV_NAME/bin:/opt/conda/bin:$PATH

RUN wget https://www.dropbox.com/s/lrvwfehqdcxoza8/saved_models.zip && \
	unzip saved_models.zip -d /models

COPY tmux.conf /root/.tmux.conf
SHELL ["/bin/bash", "-c"]

WORKDIR /workspace
CMD /bin/bash